# Numpy exercises

This is a collection of exercises that have been collected from the internet. The goal of this collection is to provide a set of exercises for users. 

NumPy is an essential toolkit for any Data science practitioner, so it is highly recommended that you don't try to copy solutions from the internet, but try to solve it yourself. 

For help check out NumPy documentation, [Numpy.org](https://numpy.org/doc/1.19/reference/index.html)

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)

1.18.5


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
n=np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [7]:
print("%d bytes" % (n.size * n.itemsize))

80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

python -c "import numpy; numpy.info(numpy.add)"

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [10]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [13]:
y=np.arange(10,50)
print(y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [18]:
y=np.arange(50)
y=y[::-1]
print(y)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [19]:
m = np.arange(9).reshape(3,3)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [20]:
nz = np.nonzero([1,2,0,0,4,0])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [21]:
q = np.eye(3)
print(q)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [28]:
foo = np.random.random((3,3,3))
print(foo)

[[[0.05852404 0.21706425 0.45870504]
  [0.04192832 0.69358367 0.84768976]
  [0.26318721 0.67529696 0.66336897]]

 [[0.21630194 0.71170798 0.7297829 ]
  [0.04494576 0.44930506 0.41349707]
  [0.53501066 0.15387836 0.65277594]]

 [[0.63598612 0.92283385 0.16053526]
  [0.9945647  0.30706127 0.5365736 ]
  [0.67055277 0.45626721 0.65534038]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [30]:
Z = np.random.random((10,10))

Zmin, Zmax = Z.min(), Z.max()

print(Zmin, Zmax)

0.0005040874788392324 0.9975251483445106


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [34]:
Z = np.random.random(30)
print(Z.mean())

0.5833545197153092


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [37]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [41]:
Z = np.ones((10,10))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan,False,False,nan,True,False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [42]:
p = np.diag(1+np.arange(4),k=-1)
print(p)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [43]:
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [44]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [45]:
b= np.tile( np.array([[0,1],[1,0]]), (4,4))
print(b)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [46]:
o = np.random.random((5,5))
omax, omin = o.max(), o.min()
o = (o - omin)/(omax - omin)
print(o)

[[0.40705471 0.01406906 0.14628037 0.83100519 0.50352513]
 [0.2287961  0.41493481 0.01298765 0.25702112 0.        ]
 [0.45831048 0.28983709 0.28044054 1.         0.85476304]
 [0.81471727 0.93118803 0.44377073 0.89984082 0.95177092]
 [0.57115636 0.88090427 0.45941528 0.26015636 0.47465104]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [5]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-5-5432efe93e2f>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [51]:
multiply = np.dot(np.ones((5,3)), np.ones((3,2)))
print(multiply)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [55]:
w = np.arange(11)
w[(3 < w) & (w <= 8)] *= -1
print(w)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [56]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [11]:
Z = np.arange(3)
print(Z ** Z)       # = [0^0, 1^1, 2^2] = [1, 1, 4]
print(2 << Z >> 2)  # = [0, 1, 2]
print(Z < - Z)      # = [False, False, False]
print(1j * Z)    # = [0 + 0.j, 0 + 1.j, 0 + 2.j]
print(Z / 1 / 1)    # = [0, 1, 2]
print(Z < Z > Z)    # ValueError


[1 1 4]
[0 1 2]
[False False False]
[0.+0.j 0.+1.j 0.+2.j]
[0. 1. 2.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

First 5 expressions are legal

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [10]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-10-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-10-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [57]:
r = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(r)), r))

[-5. -3.  3.  2.  4. -5.  9. -8.  9. -5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [58]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(np.intersect1d(a,b))

[1 2 3 4 5 6 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [62]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
# Back to sanity
_ = np.seterr(**defaults)
#An equivalent way, with a context manager:
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [64]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


<ipython-input-64-c6ff0ad7fd7b>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [66]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday,today,tomorrow)

2020-10-26 2020-10-27 2020-10-28


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [68]:
l = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(l)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [69]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [70]:
h = np.random.uniform(0,10,10)
print (h - h%1)
print (np.floor(h))
print (np.ceil(h)-1)
print (h.astype(int))
print (np.trunc(h))

[9. 8. 6. 4. 3. 9. 6. 1. 7. 4.]
[9. 8. 6. 4. 3. 9. 6. 1. 7. 4.]
[9. 8. 6. 4. 3. 9. 6. 1. 7. 4.]
[9 8 6 4 3 9 6 1 7 4]
[9. 8. 6. 4. 3. 9. 6. 1. 7. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [72]:
b = np.zeros((5,5))
b += np.arange(5)
print(b)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [77]:
def generate():
    for x in range(10):
        yield x
c = np.fromiter(generate(),dtype=float,count=-1)
print(c)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [79]:
a = np.linspace(0,1,12,endpoint=True)[1:-1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [80]:
d = np.random.random(10)
d.sort()
print(d)

[0.2163999  0.33629252 0.48652844 0.49076651 0.53917789 0.57446376
 0.68692794 0.71669201 0.75292793 0.94402477]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [81]:
s = np.arange(10)
print(np.add.reduce(s))

45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [84]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [85]:
p= np.zeros(10)
p.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [86]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.99960397 1.11723507 0.99160377 0.47238261 0.77364907 1.2062644
 0.18439934 0.73818223 1.03127701 1.01466274]
[0.15273039 1.04191613 0.16980423 0.60594475 0.04355643 0.63050347
 1.29456041 1.24358436 0.73640353 1.21857401]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [87]:
v = np.random.random(10)
v[v.argmax()] = 0
print(v)

[0.25091662 0.01574516 0.7740155  0.22321918 0.69319822 0.32995743
 0.         0.61506212 0.05568106 0.081209  ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [88]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [89]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [92]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
-1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [7]:
np.set_printoptions(threshold=10)
Z = np.zeros((25,25))
print(Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [94]:
q = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(q-v)).argmin()
print(q[index])

78
