In [1]:
#Import NumPy as np
import numpy as np

In [5]:
#Create an array of 10 zeros
zero = np.zeros(10)
print(zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
#Create an array of 10 ones
one = np.ones(10)
print(one)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [8]:
#Create an array of 10 fives
fives = np.ones(10) * 5
print(fives)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [14]:
#Create an array of the integers from 10 to 50
one_to_ten = np.arange(10, 51)
print(one_to_ten)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [17]:
#Create an array of all the even integers from 10 to 50
even_numbers = np.arange(10, 51, 2)
print(even_numbers)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [19]:
#Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(0, 9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
#Create a 3x3 identity matrix
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
#Use NumPy to generate a random number between 0 and 1
r = np.random.normal(0, 1)
print(r)

-1.0238201571790462


In [26]:
# Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
a = np.random.normal(0, 1, 25)
print(a)

[ 1.88897774  0.19440396 -0.48294337  0.60854479 -0.14647721  0.74772789
  3.42279164  1.41868996 -0.63080793 -0.12439799 -0.59533075  0.19379888
 -0.07999419 -0.61695758 -1.32918774 -1.00018452 -1.27207976  0.28877921
 -0.46851445  1.29566234  2.74332845 -0.55139911 -0.2791822   0.30543728
  2.03352   ]


In [64]:
#Create the following matrix:
#array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
#       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
#       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
#       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
#       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
#       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
#       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
#       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
#       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
#       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [62]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [61]:
#Create an array of 20 linearly spaced points between 0 and 1
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [60]:
mat = np.arange(1, 26).reshape(5, 5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [32]:
#Write code that reproduces the output shown below:

#array([[12, 13, 14, 15],
#[17, 18, 19, 20],
#[22, 23, 24, 25]])

print(mat[2:, 1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [38]:
#Write code that reproduces the output shown below:
#20
print(mat[3:4, 4:5])

[[20]]


In [43]:
#Write code that reproduces the output shown below:
#array([[ 2],
#      [ 7],
#      [12]])
print(mat[0:3, 1:2])

[[ 2]
 [ 7]
 [12]]


In [54]:
#Write code that reproduces the output shown below:
#array([21, 22, 23, 24, 25])
print(mat[4:, :])

[[21 22 23 24 25]]


In [55]:
#Write code that reproduces the output shown below:
#array([[16, 17, 18, 19, 20],
#       [21, 22, 23, 24, 25]])
print(mat[3:, :])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [56]:
#Get the sum of all the values in mat
print(np.sum(mat))

325


In [58]:
#Get the standard deviation of the values in mat
print(np.random.normal(mat))

[[-0.72922153  0.83354184  4.82861994  1.99274479  5.37851084]
 [ 6.13422128  6.68224613  9.03148703  8.66855386  9.00799586]
 [11.59897819 11.53042536 13.93867232 16.99142763 15.49357088]
 [17.03859306 16.97388102 18.42945685 16.27035965 20.15028282]
 [20.16626006 22.89018692 24.17714556 25.0576258  24.69692563]]


In [59]:
#Get the sum of all the columns in mat
print(np.sum(mat, axis=0))

[55 60 65 70 75]


We worked a lot with random data with numpy, but is there a way we can insure that we always get the same random numbers?

random() function is used to generate random numbers in Python. Not actually random, rather this is used to generate pseudo-random numbers. That implies that these randomly generated numbers can be determined.

random() function generates numbers for some values. This value is also called seed value.

How Seed Function Works ?

Seed function is used to save the state of a random function, so that it can generate same random numbers on multiple executions of the code on the same machine or on different machines (for a specific seed value). The seed value is the previous value number generated by the generator. For the first time when there is no previous value, it uses current system time.